# -*- coding: utf-8 -*-
"""solucionP05

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1E_l-UR9P-2DWyVgB9coJv2vQFFBpiwi1
"""

!pip install geopandas
!pip install utm

import geopandas as gpd
import pandas as pd
import matplotlib.pyplot as plt

data={'Id':[0,1,2,3,4]}
data.update({'Nombre':['Farmacias Ahumada','Farmacia Cruz Verde','Farmacia Cruz Verde','Farmacia Homeopatica','Farmacia Salcobrand']})
data.update({'Numeracion':[ 6345,6459,6602,7785,8111]})
data.update({'Calle':['Av Vitacura','Av Vitacura','Av Vitacura','Av Vitacura','Av Vitacura',]})
data.update({'Comuna':['Vitacura','Vitacura','Vitacura','Vitacura','Vitacura']})
data.update({'Apertura':['8:30','10:00','0:00',None,'8:00']})
data.update({'Cierre':['0:00','21:00','23:30',None,'21:00']})
data.update({'Coord':[(-33.390038,-70.57308),(-33.389525,-70.569327),(-33.388813,-70.568401),(-33.385862,-70.559234),(-33.385445,-70.555948)]})
farmacias=pd.DataFrame(data)
farmacias.head()

data=dict()
data.update({'Nombre':['BETINA 24 MG X 30 COMPRIMIDOS', 'VONTROL 30 COMPRIMIDOS', 'CARDIOASPIRINA 100 MG X50 COMPRIMIDOS', 'BISOPRIL 1,25 MG', 'LEODRIN PLUS 5600', 'SULIX 04 MG X 100 CAPSULAS', 'CILOKARE 25 MG', 'ECTIEN XR 150 MG', 'CARVEDILOL 12,5 MG', 'VASTAREL MR', 'SIAFIL 100 MG X 6 COMPRIMIDOS' ,'TRAMADOL GOTAS (GENFAR)', 'ARRUMAL 30 MG']})
data.update({'Precios':[11.900,8.900,6.550,3.970,22.840,2.300,3.200,23.690,1.070,12.590,1.600,390,29.240]})
data.update({'Farmacias':['1-2','1-3','2-3-4','0-4','1-4','1-3-4','0','2','3-4','1-2-4','0-1','2-4','2-3']})
remedios=pd.DataFrame(data)
remedios.head(10)

from shapely.geometry import Point
import utm
def to_point(x):
  return Point(utm.from_latlon(x[0],x[1]))
farmacias['Coord']=farmacias['Coord'].apply(to_point)

comunas=gpd.read_file('Comunas.shp')
gdf_farmacias=gpd.GeoDataFrame(farmacias,geometry=farmacias['Coord'])
del farmacias['Coord']

def farmaco(rem):
  print('Indice del remedio (0-9)')
  i=2
  med=rem.iloc[i]
  x=med['Farmacias']
  x=x.split("-")
  locations=[]
  for e in x:
    locations.append(int(e))
  return locations

x=farmaco(remedios)
lugar=gdf_farmacias.iloc[x]
display(lugar.head())
fig,ax=plt.subplots()
comunas.loc[comunas['COMUNA']=="VITACURA"].plot(ax=ax, color='grey')
lugar.plot(ax=ax,markersize=15,color='red',marker='o')
display(comunas.loc[comunas['COMUNA']=="VITACURA"].head())

